#!/bin/sh

prefix=/usr/local
package=jdetect
uninstall=0
force=0

fatal() { [ -n "$1" ] && echo "error: $1" >&2; exit 1; }
usage() {
cat <<USAGE
Usage: $0 [options]

Install $package, a proper java '.jar' detector for binfmts

Options:
  -h|--help     - show this page.
  --force       - run even if not root
  --prefix PATH - set prefix of install path to PATH. default is "$prefix"
  --uninstall   - uninstall $package.
                  Combine with --prefix to uninstall from a custom path

Copyright (C) 2013 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
USAGE
}

uninstall() {
	echo "TODO"
	exit
}

# pre-parse help
for arg in "$@"; do case "$arg" in -h|--help) usage; exit;; esac; done

while [ $# -gt 0 ]; do
	case "$1" in
	--prefix) shift; [ -n "$1" ] || fatal "missing prefix"; prefix="$1";;
	--uninstall) uninstall=1;;
	--force) force=1;;
	esac
	shift
done


basedir=$prefix/lib/$package
mydir=$(dirname "$0")

[ "$force" -eq 0 ] && [ $(id -u) -gt 0 ] && fatal "must be root to run, unless --force is set"

if [ "$uninstall" -gt 0 ]; then uninstall; exit; fi

mkdir -p "$basedir"

cp "$mydir"/jexec "$mydir"/jdetect "$basedir"

awk -v package="$package" -v basedir="$basedir" '{ \
	sub("%PACKAGE%", package)
	sub("%BASEDIR%", basedir)
	}1' "$mydir"/jar.binfmt.in > "$basedir"/jar.binfmt

awk -v prefix="$prefix" \
    '/^uninstall=/{sub("=.*","=1")}
     /^prefix=/   {sub("=.*","=\"" prefix "\"")}
     1' "$mydir/install" > "$basedir/uninstall"
chmod +x "$basedir/uninstall"

update-alternatives \
	--install /usr/bin/jexec jexec $basedir/jexec 1100 \
	--slave \
	    /usr/share/binfmts/jar \
	    jexec-binfmt \
	    $basedir/jar.binfmt

# remove existing entry, if any
entry=/var/lib/binfmts/jar
if [ -f "$entry" ]; then
	current=$(head -n 1 "$entry")
	update-binfmts --package "$current" --remove jar /usr/bin/jexec || true
fi

# add entry
update-binfmts --package "$package" --import jar
