#!/bin/sh

prefix=/usr/local
package=jdetect
uninstall=0

fatal() { [ -n "$1" ] && echo "error: $1" >&2; exit 1; }
usage() {
cat <<USAGE
Usage: $0 [options]

Install $package, a proper java '.jar' detector for binfmts

Options:
  -h|--help     - show this page.
  --prefix PATH - set prefix of install path to PATH. default is "$prefix"
  --uninstall   - uninstall $package.
                  Combine with --prefix to uninstall from a custom path

Copyright (C) 2013 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
USAGE
}

uninstall() {
	echo "TODO"
	exit
}

# pre-parse help
for arg in "$@"; do case "$arg" in -h|--help) usage; exit;; esac; done

while [ $# -gt 0 ]; do
	case "$1" in
	--prefix) shift; [ -n "$1" ] || fatal "missing prefix"; prefix="$1";;
	--uninstall) uninstall=1;;
	esac
	shift
done


basedir=$prefix/lib/$package
mydir=$(dirname "$0")

if [ "$uninstall" -gt 0 ]; then uninstall; exit; fi

echo "installing to $prefix"
